markdown: kramdown
highlighter: rouge
safe: false
source:      .
destination: ./site
plugins_dir:  _plugins

title: Brian's blog
url: http://briansigafoos.com
root: /

permalink: none

author:
    name: Brian Sigafoos
    email: sigafoos@gmail.com
    github: briansigafoos
    angellist: briansigafoos
    twitter: BrianSigafoos
    facebook: brian.sigafoos
    linkedin: sigafoos
    instagram: briansigafoos
    gravatar: https://www.gravatar.com/avatar/8885bbd11553eaa3cdb022cefbd0934e?s=400

comments:
    provider: disqus
    disqus:
        short_name: briansigafoos

analytics:
    provider: google
    google:
        tracking_id: 'UA-42740116-1'
        domain: 'briansigafoos.com'
